services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - "4000:8080"
    networks:
      - perplexica-network
    restart: unless-stopped

  app:
    image: itzcrazykns1337/perplexica:main
    build:
      context: .
      dockerfile: app.dockerfile
    environment:
      - SEARXNG_API_URL=http://searxng:8080
      - DATA_DIR=/home/perplexica
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - HOST=0.0.0.0        # Forzamos a Next.js a escuchar en todas las interfaces
    ports:
      - "3000:3000"         # Mapeamos el puerto del contenedor al host
    networks:
      - perplexica-network
    extra_hosts:
      - "host.docker.internal:172.16.40.217"
    volumes:
      - backend-dbstore:/home/perplexica/data
      - uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml
    restart: unless-stopped

networks:
  perplexica-network:

volumes:
  backend-dbstore:
  uploads:

